AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
Gemspec/RequiredRubyVersion:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: false
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/DotPosition:
  EnforcedStyle: leading
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Metrics/AbcSize:
  Max: 20
  Exclude:
  - '**/spec/**/*.rb'
Metrics/BlockLength:
  Exclude:
  - 'Rakefile'
  - '**/*.rake'
  - '**/*.gemspec'
  - '**/spec/**/*.rb'
Layout/LineLength:
  Max: 100
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/MethodLength:
  Max: 30
Style/AccessModifierDeclarations:
  Enabled: true
  EnforcedStyle: inline
Style/BlockDelimiters:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes

